name: Python Integration Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository code
      uses: actions/checkout@v4

    - name: Set up Python environment
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"

    - name: Install system dependencies for OpenEXR and OpenCV
      run: |
        sudo apt-get update
        # Se reemplaza libgl1-mesa-glx por libgl1 para compatibilidad nativa con Ubuntu 24.04
        sudo apt-get install -y libopenexr-dev openexr libgl1

    - name: Install Python requirements
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-dev.txt

    - name: Lint code with flake8 (Syntax check)
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Run tests
      run: pytest
